# 此处的 name 被 publish-beta.yml 引用，请勿修改！！！
name: Build APK (Release)

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: yarn

      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Install dependencies
        run: yarn install

      - name: Prebuild
        run: yarn run prebuild:android

      - name: Build Release APK
        run: |
          cd android
          echo "$SIGN_KEYSTORE_BASE64" | base64 -d > "./app/$KEYSTORE_PATH"
          ./gradlew app:packageRelease
        env:
          KEYSTORE_PATH: 'keystore.jks'
          KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGN_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
          SIGN_KEYSTORE_BASE64: ${{ secrets.SIGN_KEYSTORE_BASE64 }}
      
      - name: Extract Version Info
        shell: bash
        run: |
          echo "$(grep 'versionCode' android/app/build.gradle | awk '{print $2}')" > android/app/build/outputs/version-code
          echo "$(grep 'versionName' android/app/build.gradle | awk -F '"' '{print $2}')" > android/app/build/outputs/version-name

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: android/app/build/outputs
          retention-days: 0
